apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp-container
        image: siddanth111/nodeapps
        ports:
        - containerPort: 3000
        env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: nodeapp-config
              key: APP_NAME